Repository campfred/tg-previewsynth-bot, pull requests merged in 2024-12, with the labels that each got.

#4 docs: update docker run command (fixes #2)
  README.md
Labels: documentation

#6 Feat : API-based converters framework + Music converter
  .github/workflows/build.yml
  README.md
  config.yaml.example
  deno.json
  deno.lock
  src/admin_actions.ts
  src/config.ts
  src/converters/music.ts
  src/converters/simple.ts
  src/main.ts
  src/main_test.ts
  src/types/odesli.ts
  src/types/types.ts
  src/utils.ts
Labels: bug, documentation, enhancement

#9 Fix music conversion failing
  .github/workflows/build.yml
  README.md
  src/converters/music.ts
  src/main.ts
  src/types/odesli.ts
Labels: bug

#11 Fix GH Actions
  .github/workflows/build.yml
  src/config.ts
  src/main.ts
Labels: bug

#12 Fix configuration file error handling
  README.md
  src/config.ts
Labels: bug
